{
    "name": "CICON QA/QC ",
    "version": "0.1",
    "author": "CICON",
    "website": "http://www.cicon.ae/",
    "category": "Generic Modules/Others",
    "depends": ['cicon_prod', 'hr'],
    "data":     ['security/qc_security.xml',
                 'security/ir.model.access.csv',
                 'views/qc_summary_sheet_report.xml',
                 'views/qc_summary_view.xml',
                 'views/qc_reports.xml',
                 'views/qc_summary_seq.xml',
                 'views/qc_observation_view.xml',
                 'views/qc_check_view.xml',
                 'views/qc_material_approval_view.xml',
                 'wizard/common_report_wizard.xml',
                 'views/qc_material_approval_report.xml'
                 ],
    "description": "CICON QA/QC",
    "init_xml": [],
    'update_xml': [],
    "demo_xml": [],
    "active": False,
    "installable": True
}
